moved mkl/blas checking functions into a separate section.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -414,6 +414,53 @@ fi
 
 }
 
+
+#  !---------------------------------------------------------------------!
+#  ! External library checking                                           !
+#  !---------------------------------------------------------------------!
+
+# Function to check for mkl library and dependencies.
+check_mkl(){
+  if [ -z $MKLROOT ]; then
+    echo "MKL is not loaded. Inbuilt diagonalizer will be used."
+    return 1
+  fi
+
+  MKLLIBPATH=$MKLROOT/lib/intel64
+  if [ ! -e "$MKLLIBPATH/libmkl_intel_lp64.so" ]; then
+    echo "libmkl_intel_lp64.so cannot be found. Inbuilt diagonalizer will be used."
+    return 1
+  fi
+
+  if [ ! -e "$MKLLIBPATH/libmkl_intel_thread.so" ]; then
+    echo "libmkl_intel_thread.so cannot be found. Inbuilt diagonalizer will be used."
+    return 1
+  fi
+
+  if [ ! -e "$MKLLIBPATH/libmkl_core.so" ]; then
+    echo "libmkl_core.so cannot be found. Inbuilt diagonalizer will be used."
+    return 1
+  fi
+
+  echo "MKL is loaded. Diagonalizer from MKL will be used."
+}
+
+
+# Function to check for lapack library and dependencies.
+check_lapack(){
+  if [ -z $EBROOTOPENBLAS ] || [ -z "$BLASDIR" ]; then
+    echo "OPENBLAS is not loaded. Inbuilt diagonalizer will be used."
+    return 1
+  fi
+
+  if [ ! -e "$EBROOTOPENBLAS/lib/libopenblas.so" ] && [ -e "$BLASDIR/lib/libopenblas.so"];then
+    echo "libopenblas.so cannot be found. Inbuilt diagonalizer will be used."
+  fi
+
+  echo "OPENBLAS is loaded. Diagonalizer from LAPACK will be used."
+}
+
+
 #  !---------------------------------------------------------------------!
 #  ! Variable definitions                                                !
 #  !---------------------------------------------------------------------!
@@ -902,49 +949,6 @@ fi
 #  ! Set flags & generate make input files                               !
 #  !---------------------------------------------------------------------!
 
-# Function to check for MIRP library and dependencies.
-check_mkl(){
-	if [ -z $MKLROOT ]; then
-		echo "MKL is not loaded. Inbuilt diagonalizer will be used."
-		return 1
-	fi
-
-	MKLLIBPATH=$MKLROOT/lib/intel64
-	if [ ! -e "$MKLLIBPATH/libmkl_intel_lp64.so" ]; then
-		echo "libmkl_intel_lp64.so cannot be found. Inbuilt diagonalizer will be used."
-		return 1
-	fi
-
-	if [ ! -e "$MKLLIBPATH/libmkl_intel_thread.so" ]; then
-        echo "libmkl_intel_thread.so cannot be found. Inbuilt diagonalizer will be used."
-        return 1
-    fi
-
-	if [ ! -e "$MKLLIBPATH/libmkl_core.so" ]; then
-        echo "libmkl_core.so cannot be found. Inbuilt diagonalizer will be used."
-        return 1
-    fi
-
-	echo "MKL is loaded. Diagonalizer from MKL will be used."
-	fort_flags="$fort_flags -DMKL"
-	ldflags="$ldflags -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread"
-}
-
-check_lapack(){
-	if [ -z $EBROOTOPENBLAS ] || [ -z "$BLASDIR" ]; then
-        echo "OPENBLAS is not loaded. Inbuilt diagonalizer will be used."
-        return 1
-    fi
-	
-	if [ ! -e "$EBROOTOPENBLAS/lib/libopenblas.so" ] && [ -e "$BLASDIR/lib/libopenblas.so"];then
-		echo "libopenblas.so cannot be found. Inbuilt diagonalizer will be used."
-	fi
-
-	echo "OPENBLAS is loaded. Diagonalizer from LAPACK will be used."
-	fort_flags="$fort_flags -DLAPACK"
-	ldflags="$ldflags -lopenblas"
-}
-
 for buildtype in $buildtypes; do
 
   # set compiler specific flags
@@ -1027,10 +1031,19 @@ for buildtype in $buildtypes; do
   # For serial and mpi versions, diagonalizers from lapack/mkl may be used
   if [ "$buildtype" = 'serial' -o "$buildtype" = 'mpi' ]; then
     if [ "$lapack" = 'yes' ]; then
-		check_lapack
-	elif [ "$mkl" = 'yes' ]; then
-		check_mkl
-	fi
+      check_lapack
+      if [ "$?" -eq 0 ]; then
+        fort_flags="$fort_flags -DMKL"
+        ldflags="$ldflags -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread"
+      fi
+
+    elif [ "$mkl" = 'yes' ]; then
+      check_mkl
+      if [ "$?" -eq 0 ]; then
+        fort_flags="$fort_flags -DLAPACK"
+        ldflags="$ldflags -lopenblas"
+      fi
+    fi
   fi
 
   # set the installer
