updated to configure with --mirp, removed mirp configuration info from help

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -62,9 +62,6 @@ echo  "
       --amber        Install QUICK executables and libaries into AMBER. 
                      Requires specifying AMBER home directory as prefix. 
       --verbose      Enable full compilation output
-      --mirp         Use functions for ERI calculations from MIRP library. 
-                     The MIRP libary, header files and their dependencies must
-                     be available in QUICK_HOME/dependencies directory.
 
   Supported compilers are: gnu, intel, pgi, nvidia
 
@@ -415,6 +412,60 @@ fi
 
 }
 
+# Function to check for MIRP library and dependencies. 
+check_mirp(){
+
+if [ "$mirp" = 'yes' ] && [ "$shared" = 'no' ]; then
+  echo "Error: MIRP requires --shared flag. Plese reconfigure."
+  exit 1
+fi
+
+if [ -z "$MIRP_HOME" ]; then
+  echo "Error: MIRP_HOME is not set!"
+  exit 1
+else
+ # check for the so library
+  if [ ! -e "$MIRP_HOME/lib/libmirp.so" ]; then
+    echo "Error: libmirp.so cannot be found!"
+    exit 1
+  fi
+fi
+
+# check for dependencies
+if [ -z "$MIRP_DEP_HOME" ]; then
+  echo "Error: MIRP_DEP_HOME is not set!"
+  exit 1
+else
+
+# check for libarb.so
+if [ ! -e "$MIRP_DEP_HOME/lib/libarb.so" ]; then
+   echo "Error: libarb.so cannot be found!"
+   exit 1
+fi
+
+# check for libgmp.so
+if [ ! -e "$MIRP_DEP_HOME/lib/libgmp.so" ]; then
+   echo "Error: libgmp.so cannot be found!"
+   exit 1
+fi
+
+# check for libmpfr.so
+if [ ! -e "$MIRP_DEP_HOME/lib/libmpfr.so" ]; then
+   echo "Error: libmpfr.so cannot be found!"
+   exit 1
+fi
+
+# check for libflint.so
+if [ ! -e "$MIRP_DEP_HOME/lib/libflint.so" ]; then
+   echo "Error: libflint.so cannot be found!"
+   exit 1
+fi
+
+fi
+
+}
+
+
 #  !---------------------------------------------------------------------!
 #  ! Variable definitions                                                !
 #  !---------------------------------------------------------------------!
@@ -516,6 +567,9 @@ aminstall='false'
 # control compiler output
 verbose='@'
 
+# flag for mirp library
+mirp='no'
+
 #  !---------------------------------------------------------------------!
 #  ! Check user input                                                    !
 #  !---------------------------------------------------------------------!
@@ -530,6 +584,7 @@ while [ $# -gt 0 ]; do
     --debug-time)  debugtime='yes';;
     --debug)       debug='yes';;
     --verbose)     verbose='';;
+    --mirp)        mirp='yes';;
     --shared)      shared='yes';;
     --nof)         nof='yes';;
     --amber)       aminstall='true';;
@@ -567,6 +622,11 @@ fi
 
 # check compiler
 check_compiler
+
+# check for dependencies
+if [ "$mirp" = "yes" ]; then
+  check_mirp
+fi
 
 # check is amber installtion is required
 if [ "$aminstall" = "true" ]; then
@@ -976,6 +1036,14 @@ for buildtype in $buildtypes; do
     set_mpicxx
   fi
 
+  # set mirp library flags
+  if [ "$buildtype" = 'serial' -o "$buildtype" = 'mpi' ]; then
+    if [ "$mirp" = "yes" ]; then
+      cxx_flags="$cxx_flags -I$MIRP_HOME/include -I$MIRP_DEP_HOME/include"
+      ldflags="$ldflags -L$MIRP_HOME/lib -lmirp"
+    fi
+  fi
+
   # set the installer
   installer=''
   if [ "$buildtype" = 'serial' ]; then
@@ -1003,6 +1071,7 @@ for buildtype in $buildtypes; do
     libxcobjfolder="$QUICK_HOME/build/common/gpu/libxcobj"
     libxcdevobjfolder="$QUICK_HOME/build/common/gpu/libxcdevobj"
   fi
+
 
   # copy template Makefile into each buildtype directory
   cp -f "$QUICK_HOME/tools/build-makefile" "$QUICK_HOME/build/Makefile"
@@ -1169,6 +1238,12 @@ else
   for buildtype in $buildtypes; do
     libpaths="$libpath/$buildtype:$libpaths"
   done
+fi
+
+if [ "$buildtype" = 'serial' -o "$buildtype" = 'mpi' ]; then
+  if [ "$mirp" = "yes" ]; then
+    libpaths="$MIRP_HOME/lib:$MIRP_DEP_HOME/lib:$libpaths"
+  fi
 fi
 
 cat >> "$quick_prefix/quick.rc" << EOF
