removed amprefix; added --amber flag for amber compatible installation; removed AMBER_HOME/bin folder check

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -56,8 +56,8 @@ echo  "
       --nof          Disables the compilation of time consuming f functions
                      in the ERI code of cuda version. Not recommended for
                      production.
-      --amprefix <dir>
-                     Path to AMBER home directory
+      --amber        Install QUICK executables and libaries into AMBER. 
+                     Requires specifying AMBER home directory as prefix. 
 
   Supported compilers are: gnu, intel
 
@@ -432,7 +432,7 @@ ncores=''
 nof='no'
 
 # amber related variables
-useamprefix='false'
+aminstall='false'
 amprefix=''
 
 #  !---------------------------------------------------------------------!
@@ -449,10 +449,10 @@ while [ $# -gt 0 ]; do
     --debug)       debug='yes';;
     --shared)      shared='yes';;
     --nof)         nof='yes';;
+    --amber)       aminstall='true';;
     --arch)        shift; cuda_arch="$cuda_arch $1"; uspec_arch='true';;
     --ncores)      shift; ncores=$1; uspec_ncores='yes';;
     --prefix)      shift; quick_prefix=${1%/}; useprefix='true';;
-    --amprefix)    shift; amprefix=${1%/}; useamprefix='true';;
     gnu)           compiler='gnu';;
     intel)         compiler='intel';;
     -h| -H| -help| --help) print_help;;
@@ -483,8 +483,38 @@ fi
 # check compiler
 check_compiler
 
-# check prefix and perform necessary operations
-if [ "$useprefix" = "true" ]; then
+# check is amber installtion is required
+if [ "$aminstall" = "true" ]; then
+
+  if [ "$useprefix" = "false" ]; then
+    echo "Error: AMBER compatible installation requires specifying the AMBER home directory as prefix."
+    exit 1
+  fi
+
+  # check for AMBER_HOME
+  if [ ! -d "$quick_prefix/AmberTools" ]; then
+    echo  "Error: Please provide the correct AMBER home directory."
+    exit 1
+  else
+    # do this trick to get absolute path
+    cd "$quick_prefix"
+    amprefix=`pwd`
+    cd "$QUICK_HOME"
+
+    echo "QUICK will be installed into $amprefix."
+
+    installtypes='aminstall'
+    uninstalltypes='amuninstall'
+
+    # reset $quick_prefix to prevent copying test script into AMBER_HOME
+    quick_prefix="$QUICK_HOME"    
+
+  fi
+
+fi
+
+# check prefix and perform necessary operations, we shall not create these for an amber installation
+if [ "$useprefix" = "true" ] && [ "$aminstall" = "false" ]; then
 
   if [ "$QUICK_HOME" = "$quick_prefix" ]; then
     echo  "Error: Specified --prefix and current folder is the same. Please choose a different location. "
@@ -543,30 +573,12 @@ if [ "$useprefix" = "true" ]; then
     installtypes="$installtypes $buildtype$install_string"
     uninstalltypes="$uninstalltypes $buildtype$uninstall_string"
   done
-
-else
-
-  echo "No prefix specified for the installation."
-
-  installtypes='noinstall'
-  uninstalltypes='nouninstall'
-
 fi
 
-# check amber prefix
-if [ "$useamprefix" = "true" ]; then
-
-  # do this trick to get absolute path
-  cd "$amprefix"
-  amprefix=`pwd`
-  cd "$QUICK_HOME"
-
-  if [ ! -d "$amprefix/bin" ]; then
-    echo  "Error: $amprefix/bin not found."
-    exit 1
-  else
-    echo "QUICK executables will be installed in $amprefix/bin folder."
-  fi
+if [ "$useprefix" = "false" ]; then
+  echo "No prefix specified for the installation."
+  installtypes='noinstall'
+  uninstalltypes='nouninstall'
 fi
 
 
@@ -859,7 +871,7 @@ for buildtype in $buildtypes; do
   fi
 
   # set the test type
-  if [ "$useprefix" = "true" ]; then
+  if [ "$useprefix" = "true" ] && [ "$aminstall" = "false" ]; then
     testtype='installtest'
   fi
 
@@ -988,7 +1000,6 @@ SHARED=$shared
 
 INSTALLTYPES=$installtypes
 UNINSTALLTYPES=$uninstalltypes
-AMINSTALL=$useamprefix
 
 TESTTYPE=$testtype
 
@@ -1031,6 +1042,6 @@ fi
 
 echo  "          Run 'make test' to verify the executables."
 
-if [ "$useamprefix" = "true" ]; then
-echo  "          Run 'make aminstall' to install QUICK executables in $amprefix."
+if [ "$aminstall" = "true" ]; then
+echo  "          Run 'make install' to install QUICK executables and libraries into $amprefix."
 fi
