updated to test hip and hipmpi executables

diff --git a/tools/runtest b/tools/runtest
--- a/tools/runtest
+++ b/tools/runtest
@@ -41,6 +41,8 @@ serial='no'
 mpi='no'
 cuda='no'
 cudampi='no'
+hip='no'
+hipmpi='no'
 apiexe=''
 
 # test list file
@@ -89,8 +91,10 @@ echo  "
   Available flags are:                                                      
       --serial       Tests QUICK serial version                                
       --mpi          Tests QUICK MPI parallel version                           
-      --cuda         Tests QUICK GPU version
-      --cudampi      Tests QUICK multi-GPU version
+      --cuda         Tests QUICK NVIDIA GPU version
+      --cudampi      Tests QUICK NVIDIA multi-GPU version
+      --hip          Tests QUICK AMD GPU version
+      --hipmpi       Tests QUICK AMD multi-GPU version
       --ene          Run only energy tests
       --grad         Run only gradient tests
       --opt          Run only geometry optimization tests
@@ -374,6 +378,36 @@ set_qexe_testlist(){
     else
       test_list="$testdir/testlist_short_cuda.txt"
     fi
+  elif [ "$buildtype" = 'hip' ]; then
+    qexe='quick.hip'
+    apiexe='test-api.hip'
+
+    if [ -x "$testdir/test-api.hip" ]; then
+      apipath=$testdir
+    elif [ -x "$qbindir/test-api.hip" ]; then
+      apipath=$qbindir
+    fi
+
+    if [ "$test_length" = 'full' ]; then
+      test_list="$testdir/testlist_full_cuda.txt"
+    else
+      test_list="$testdir/testlist_short_cuda.txt"
+    fi
+  elif [ "$buildtype" = 'hipmpi' ]; then
+    qexe='quick.hip.MPI'
+    apiexe='test-api.hip.MPI'
+
+    if [ -x "$testdir/test-api.hip.MPI" ]; then
+      apipath=$testdir
+    elif [ -x "$qbindir/test-api.hip.MPI" ]; then
+      apipath=$qbindir
+    fi
+
+    if [ "$test_length" = 'full' ]; then
+      test_list="$testdir/testlist_full_cuda.txt"
+    else
+      test_list="$testdir/testlist_short_cuda.txt"
+    fi
   fi
 
 }
@@ -424,7 +458,7 @@ run_test(){
     print_test_info "$t"
 
     # Run the test case
-    if [ $buildtype = 'mpi' ] || [ $buildtype = 'cudampi' ] && [ $ismpirun = 'yes' ]; then
+    if [ $buildtype = 'mpi' ] || [ $buildtype = 'cudampi' ] || [ $buildtype = 'hipmpi' ] && [ $ismpirun = 'yes' ]; then
       $DO_PARALLEL "$qbindir/$qexe" "$t.in" > /dev/null 2>&1
     else
       "$qbindir/$qexe" "$t.in" > /dev/null 2>&1
@@ -445,7 +479,7 @@ run_api_test(){
     print_test_info "$t"
    
     #Run test
-    if [ $buildtype = 'mpi' ] || [ $buildtype = 'cudampi' ] && [ $ismpirun = 'yes' ]; then
+    if [ $buildtype = 'mpi' ] || [ $buildtype = 'cudampi' ] || [ $buildtype = 'hipmpi' ] && [ $ismpirun = 'yes' ]; then
       $DO_PARALLEL "$apipath/$apiexe" > /dev/null 2>&1
     else
       "$apipath/$apiexe" > /dev/null 2>&1
@@ -622,6 +656,8 @@ while [ $# -gt 0 ]; do
     --mpi)         mpi='yes'; buildtypes="$buildtypes mpi";;
     --cuda)        cuda='yes'; buildtypes="$buildtypes cuda";;
     --cudampi)     cudampi='yes'; buildtypes="$buildtypes cudampi";;
+    --hip)         hip='yes'; buildtypes="$buildtypes hip";;
+    --hipmpi)      hipmpi='yes'; buildtypes="$buildtypes hipmpi";;
     --ene)         test_ene='yes';uspec_test='yes';;
     --grad)        test_grad='yes';uspec_test='yes';;
     --opt)         test_opt='yes';uspec_test='yes';;
@@ -656,7 +692,7 @@ if [ ! -d "$testdir" ]; then
   exit 1
 fi
 
-if [ "$serial" = 'yes' -o "$mpi" = 'yes' -o "$cuda" = 'yes' -o "$cudampi" = 'yes' ]; then
+if [ "$serial" = 'yes' -o "$mpi" = 'yes' -o "$cuda" = 'yes' -o "$cudampi" = 'yes' -o "$hip" = 'yes' -o "$hipmpi" = 'yes' ]; then
 
   if [ "$serial" = 'yes' ]; then
     if [ ! -x "$qbindir/quick" ]; then
@@ -702,6 +738,28 @@ if [ "$serial" = 'yes' -o "$mpi" = 'yes' -o "$cuda" = 'yes' -o "$cudampi" = 'yes
     fi
   fi
 
+  if [ "$hip" = 'yes' ]; then
+    if [ ! -x "$qbindir/quick.hip" ]; then
+      echo  "Error: $qbindir/quick.hip not found."
+      exit 1
+    fi
+    if ! [ -x "$testdir/test-api.hip" -o -x "$qbindir/test-api.hip" ]; then
+      echo  "Error: test-api.hip not found in $testdir or $qbindir."
+      exit 1
+    fi
+  fi
+
+  if [ "$hipmpi" = 'yes' ]; then
+    if [ ! -x "$qbindir/quick.hip.MPI" ]; then
+      echo  "Error: $qbindir/quick.hip.MPI not found."
+      exit 1
+    fi
+    if ! [ -x "$testdir/test-api.hip.MPI" -o -x "$qbindir/test-api.hip.MPI" ]; then
+      echo  "Error: test-api.hip.MPI not found in $testdir or $qbindir."
+      exit 1
+    fi
+  fi
+
 else
 
   # automatically check for executables
@@ -715,6 +773,16 @@ else
     buildtypes="$buildtypes cuda"
   fi
 
+  if [ -x "$qbindir/quick.hip.MPI" ]; then
+    hipmpi='yes'
+    buildtypes="$buildtypes hipmpi"
+  fi
+
+  if [ -x "$qbindir/quick.hip" ]; then
+    hip='yes'
+    buildtypes="$buildtypes hip"
+  fi
+
   if [ -x "$qbindir/quick.MPI" ]; then
     mpi='yes'
     buildtypes="$buildtypes mpi"
@@ -725,7 +793,8 @@ else
     buildtypes="$buildtypes serial"
   fi
 
-  if [ "$serial" = 'no' -a "$mpi" = 'no' -a "$cuda" = 'no' -a "$cudampi" = 'no' ]; then
+
+  if [ "$serial" = 'no' -a "$mpi" = 'no' -a "$cuda" = 'no' -a "$cudampi" = 'no' -a "$hip" = 'no' -a "$hipmpi" = 'no' ]; then
     echo  "Error: No QUICK executables found in $qbindir. "
     exit 1
   fi
@@ -754,7 +823,7 @@ fi
 
 
 # check for mpirun 
-if [ "$mpi" = 'yes' -o "$cudampi" = 'yes' ]; then
+if [ "$mpi" = 'yes' -o "$cudampi" = 'yes' -o "$hipmpi" = 'yes' ]; then
    mpimsg=""
    if [ -z "$DO_PARALLEL" ]; then
      echo "Error: MPI/CUDAMPI tests are requested but DO_PARALLEL variable is not set."
@@ -775,6 +844,11 @@ if [ "$mpi" = 'yes' -o "$cudampi" = 'yes' ]; then
    if [ "$cudampi" = 'yes' ]; then
      echo "" >> $QUICK_HOME/.quick.cudampi.runtest.log
      echo "$mpimsg" >> $QUICK_HOME/.quick.cudampi.runtest.log
+   fi
+
+   if [ "$hipmpi" = 'yes' ]; then
+     echo "" >> $QUICK_HOME/.quick.hipmpi.runtest.log
+     echo "$mpimsg" >> $QUICK_HOME/.quick.hipmpi.runtest.log
    fi
 
 fi
