AWG Update runtest script for Amber
In Amber
- Assume this runtest script gets installed into $AMBERHOME/AmberTools/src/quick/
- While binaries are in $AMBERHOME/bin.

This update will make sure we find the binary folder.

diff --git a/tools/runtest b/tools/runtest
--- a/tools/runtest
+++ b/tools/runtest
@@ -701,8 +701,13 @@ done
 #  !---------------------------------------------------------------------!
 
 if [ ! -d "$qbindir" ]; then
-  echo  "Error: QUICK bin folder not found. "
-  exit 1
+  if [ "$AMBERHOME" != "" ]; then
+    # Assume we are in Amber
+    qbindir=$AMBERHOME/bin
+  else
+    echo  "Error: QUICK bin folder not found. "
+    exit 1
+  fi
 fi
 
 if [ ! -d "$qbasisdir" ]; then
